// Lightweight, dependency-free exporters for AI outputs.
// - PDF: opens a styled print window (user picks "Save as PDF")
// - Word: downloads a .doc (Word opens HTML-as-doc natively)
// - ICS: builds a minimal calendar event from a title + date

function download(filename: string, mime: string, content: BlobPart) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1500);
}

function safeName(s: string) {
  return (s || "prodai-output").replace(/[^a-z0-9-_]+/gi, "_").slice(0, 60);
}

// Very small markdown → HTML for export readability.
function mdToHtml(md: string): string {
  const esc = (s: string) =>
    s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  const lines = md.split("\n");
  let html = "";
  let inList: "ul" | "ol" | null = null;
  let inTable = false;
  let inCode = false;
  const flushList = () => { if (inList) { html += `</${inList}>`; inList = null; } };
  const flushTable = () => { if (inTable) { html += "</tbody></table>"; inTable = false; } };
  for (let raw of lines) {
    if (raw.startsWith("```")) {
      flushList(); flushTable();
      if (!inCode) { html += "<pre><code>"; inCode = true; } else { html += "</code></pre>"; inCode = false; }
      continue;
    }
    if (inCode) { html += esc(raw) + "\n"; continue; }
    const line = raw.trimEnd();
    if (/^\|.+\|$/.test(line)) {
      const cells = line.slice(1, -1).split("|").map((c) => esc(c.trim()));
      if (!inTable) { html += "<table><tbody>"; inTable = true; }
      if (/^\|?\s*:?-+/.test(line)) continue; // separator
      html += "<tr>" + cells.map((c) => `<td>${c}</td>`).join("") + "</tr>";
      continue;
    } else flushTable();
    const h = line.match(/^(#{1,6})\s+(.*)$/);
    if (h) { flushList(); html += `<h${h[1].length}>${esc(h[2])}</h${h[1].length}>`; continue; }
    if (/^[-*]\s+/.test(line)) {
      if (inList !== "ul") { flushList(); html += "<ul>"; inList = "ul"; }
      html += `<li>${formatInline(esc(line.replace(/^[-*]\s+/, "")))}</li>`;
      continue;
    }
    if (/^\d+\.\s+/.test(line)) {
      if (inList !== "ol") { flushList(); html += "<ol>"; inList = "ol"; }
      html += `<li>${formatInline(esc(line.replace(/^\d+\.\s+/, "")))}</li>`;
      continue;
    }
    flushList();
    if (line.trim() === "") html += "<p></p>";
    else html += `<p>${formatInline(esc(line))}</p>`;
  }
  flushList(); flushTable();
  if (inCode) html += "</code></pre>";
  return html;
}
function formatInline(s: string) {
  return s
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/`([^`]+)`/g, "<code>$1</code>");
}

const baseStyle = `
  body{font-family:-apple-system,Segoe UI,Roboto,sans-serif;color:#111;max-width:720px;margin:32px auto;padding:0 24px;line-height:1.5}
  h1,h2,h3,h4{color:#0f172a;margin:18px 0 8px} h1{font-size:22px} h2{font-size:18px} h3{font-size:16px}
  p{margin:8px 0} ul,ol{padding-left:22px} li{margin:3px 0}
  table{border-collapse:collapse;width:100%;margin:10px 0;font-size:13px}
  td{border:1px solid #cbd5e1;padding:6px 8px;vertical-align:top}
  tr:first-child td{background:#f1f5f9;font-weight:600}
  pre{background:#f8fafc;padding:12px;border-radius:6px;overflow:auto}
  code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px}
  .footer{margin-top:24px;padding-top:12px;border-top:1px solid #e2e8f0;color:#64748b;font-size:11px}
`;

export function exportPdf(title: string, markdown: string) {
  const win = window.open("", "_blank", "noopener,width=900,height=900");
  if (!win) return;
  win.document.write(`<!doctype html><html><head><title>${title}</title><meta charset="utf-8"><style>${baseStyle}</style></head><body><h1>${title}</h1>${mdToHtml(markdown)}<div class="footer">AI-generated by ProdAI Assistant — please review for accuracy.</div><script>setTimeout(()=>window.print(),250)</script></body></html>`);
  win.document.close();
}

export function exportDoc(title: string, markdown: string) {
  const html = `<!doctype html><html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word"><head><meta charset="utf-8"><title>${title}</title><style>${baseStyle}</style></head><body><h1>${title}</h1>${mdToHtml(markdown)}<div class="footer">AI-generated by ProdAI Assistant — please review for accuracy.</div></body></html>`;
  download(`${safeName(title)}.doc`, "application/msword", html);
}

export function exportIcs(title: string, when?: Date, durationMin = 30, description = "") {
  const dt = when ?? new Date(Date.now() + 24 * 3600 * 1000);
  const fmt = (d: Date) => d.toISOString().replace(/[-:]/g, "").replace(/\.\d{3}/, "");
  const end = new Date(dt.getTime() + durationMin * 60000);
  const ics = [
    "BEGIN:VCALENDAR", "VERSION:2.0", "PRODID:-//ProdAI Assistant//EN",
    "BEGIN:VEVENT",
    `UID:${crypto.randomUUID()}@prodai`,
    `DTSTAMP:${fmt(new Date())}`,
    `DTSTART:${fmt(dt)}`,
    `DTEND:${fmt(end)}`,
    `SUMMARY:${title.replace(/\n/g, " ")}`,
    `DESCRIPTION:${description.replace(/\n/g, "\\n").slice(0, 800)}`,
    "END:VEVENT", "END:VCALENDAR",
  ].join("\r\n");
  download(`${safeName(title)}.ics`, "text/calendar", ics);
}
