import { ShieldCheck } from "lucide-react";
import { useState, type ReactNode } from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";

export function ResponsibleAIDialog({ trigger }: { trigger: ReactNode }) {
  const [open, setOpen] = useState(false);
  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>{trigger}</DialogTrigger>
      <DialogContent className="max-w-lg">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <ShieldCheck className="h-5 w-5 text-primary" /> Responsible AI
          </DialogTitle>
          <DialogDescription>
            How ProdAI uses AI — and how to use it well.
          </DialogDescription>
        </DialogHeader>
        <div className="space-y-4 text-sm leading-relaxed">
          <Section title="Limitations">
            Outputs are generated by a large language model. They can be
            confidently wrong, miss recent context, or invent names, dates,
            and figures. Treat every output as a first draft.
          </Section>
          <Section title="Bias mitigation">
            Models reflect biases present in their training data. Review
            tone, gendered language, and assumptions about audiences before
            sending. Prefer inclusive, neutral phrasing.
          </Section>
          <Section title="Best practices">
            <ul className="ml-4 list-disc space-y-1">
              <li>Always read and edit AI drafts before sharing externally.</li>
              <li>Verify names, numbers, dates, and quotes against source notes.</li>
              <li>Don't paste secrets, credentials, or regulated personal data.</li>
              <li>Keep a human in the loop for hiring, legal, medical, or financial decisions.</li>
            </ul>
          </Section>
          <p className="rounded-md border border-amber-500/30 bg-amber-500/10 px-3 py-2 text-xs text-amber-700 dark:text-amber-300">
            ⚠️ AI-generated content may be inaccurate. You are responsible for what you send.
          </p>
        </div>
      </DialogContent>
    </Dialog>
  );
}

function Section({ title, children }: { title: string; children: ReactNode }) {
  return (
    <div>
      <h4 className="mb-1 text-sm font-semibold">{title}</h4>
      <div className="text-muted-foreground">{children}</div>
    </div>
  );
}
